### ISSUE TITLE
At least make an executable version if you're gonna compete with an executable.

### ISSUE THREAD

**Issue by PPPDUD** [michaeleldar/OpenSUIT#2]

**Comment by michaeleldar** [comment]
How then?

**Comment by michaeleldar** [comment]
Also I have a monopoly over the linux and mac OS market, and that's about half of the AT's

**Comment by themysticsavages** [comment]
> Also I have a monopoly over the linux and mac OS market, and that's about half of the AT's

That is, the AT'ers that need to do such a trivial task :\

**Comment by PPPDUD** [comment]
One word: PyInstaller.

**Comment by themysticsavages** [comment]
> One word: PyInstaller.

You can "One word" anything, can't you? Do we even need an executable? The AT users aren't stupid

**Comment by PPPDUD** [comment]
Maybe they wouldn't want to waste time and space for the sole purpose of
running a single program.
Or, maybe they have a school computer and aren't allowed to install
programs.

**Comment by themysticsavages** [comment]
> Maybe they wouldn't want to waste time and space for the sole purpose of running a single program. Or, maybe they have a school computer and aren't allowed to install programs.

You can use a standalone Python interpreter or just access the API directly in the browser. Executables also have security issues since you can't view the source (unless you decompile it), which usually leads to these files being outright blocked on school computers.

**Comment by PPPDUD** [comment]
Where would I get a standalone interpreter? I thought I was one of the few
people who made those things.

**Comment by themysticsavages** [comment]
> Where would I get a standalone interpreter? I thought I was one of the few people who made those things.

[Here.](https://github.com/indygreg/python-build-standalone/releases)

**Comment by PPPDUD** [comment]
I don't see any files the average Windows user can open without special
tools.

**Comment by themysticsavages** [comment]
> I don't see any files the average Windows user can open without special tools.

`tar` is a standard Windows utility as of 2018.

Just open Command Prompt or Powershell in the same directory as the tar.gz file, and run this:

```cmd
tar -xvzf cpython-*
cd python
.\python.exe
```

And if a user doesn't know how to run the command, they probably wouldn't understand the utility of the program.

**Comment by PPPDUD** [comment]
Most logical people wouldn't want to use overcomplicated and odd commands
like that for simply using a single program.

**Comment by themysticsavages** [comment]
> Most logical people wouldn't want to use overcomplicated and odd commands like that for simply using a single program.

Every single command makes sense, and if we had a PyInstaller build, it would be slow, would only work on one platform, and a "logical" person (aka not tech-savvy) would not understand SUIT's purpose. When would they ever need a username's ID?

**Comment by PPPDUD** [comment]
Whenever they're curious about who's the XXXXXth Scratcher, of course.

**Comment by themysticsavages** [comment]
> Whenever they're curious about who's the XXXXXth Scratcher, of course.

Not everyone is indexed on the SUI API, the first user in the index is [tammy](https://sui.sid72020123.repl.co/get_user/141), and people can **still** use the direct API in the browser, which works practically anywhere.

**Comment by michaeleldar** [comment]
I can't get pyinstaller to generate .exe .dmg .deb etc though. How do you do it?

**Comment by PPPDUD** [comment]
pyinstaller myname.py --onefile
This will create an executable that should work on any computer with the
same architecture and OS as you.

**Comment by michaeleldar** [comment]
Doing it today
